#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Lint Shell Files"

on:
  pull_request:
    paths:
      - "**/*.sh"
      - "**/*.rc"
      - "!**/node_modules/**"
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
  workflow_dispatch:

jobs:
  shellcheck:
    name: lint-shell
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@66c9a47bf02255b250284a82251cb4cadf5043f5 # tag=v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          path: "."
          pattern: |
            *.sh
            *.rc
          exclude: |
            ./.git/*
            ./**/node_modules/*
          check_all_files_with_shebangs: false
          fail_on_error: false
          level: warning
          shellcheck_flags: "--external-sources"
